#!/bin/sh
#
## Youtube URL handler for Firejail
#+ (1) `firejail-handler-youtube.desktop` defines a custom
#+ protocol handler for Youtube hyperlinks
#+ (2) a user.js script in the web browser turns 'https://www.youtube.com/watch?v=foo'
#+ links into 'fjyt://www.youtube.com/watch?v=foo'
#+ (3) pointing the web browser to this script will save a drop file containing
#+ the relevant URL at a read/write accessible location inside the sandbox
#+ (4) outside the sandbox `firejail-handler-youtube-ctl` uses inotifywait to pick up
#+ the URL and relays it to a fully sandboxed media player
#+ (defaults to mpv)

# shellcheck disable=SC2034

### vars
## source common settings
_settings_file="firejail-handler-settings-extra.inc"
if [ -f "${HOME}/.config/firejail/${_settings_file}" ]; then
    #+ use settings defined by user
    . "${HOME}/.config/firejail/${_settings_file}"
elif [ -f "/etc/firejail/${_settings_file}" ]; then
    #+ use system-wide settings
    . "/etc/firejail/${_settings_file}"
else
    #+ fall back to hard-coded values
    if [ "$(which xdg-user-dir)" ]; then
	_drop_dir="$(which xdg-user-dir DOWNLOAD)"
    else
	_xdg_config_home="$(env | grep -c "XDG_CONFIG_HOME")"
	if [ "$_xdg_config_home" = 1 ]; then
	    if [ -s "${XDG_CONFIG_HOME}/.config/user-dirs.dirs" ]; then
		_drop_dir="$(grep "^XDG_DOWNLOAD_DIR=" "${XDG_CONFIG_HOME}/.config/user-dirs.dirs" | awk '{split($0,a,"="); print a[2]}' | sed 's/"//g')"
	    fi
	elif [ -s "${HOME}/.config/user-dirs.dirs" ]; then
	    _drop_dir="$(grep "^XDG_DOWNLOAD_DIR=" "${HOME}/.config/user-dirs.dirs" | awk '{split($0,a,"="); print a[2]}' | sed 's/"//g')"
	else
	    _drop_dir="${HOME}/Downloads"
	fi
    fi
    # bittorrent client watch dir for .torrent files
    _download_dir="$_drop_dir"
    ## drop dir location where the URL data will be saved temporarily
    #+ IMPORTANT: this needs to be read/write accessible in the sandbox
    _drop_dir="${_drop_dir}/.firejail-dropzone"
    ## protocol handlers
    #+ bittorrent
    _drop_file_bt="${_drop_dir}/bittorrent.drop"
    _media_dl_mode="local"
    _rpc_bin="/usr/local/bin/transmission-remote"
    _rpc_port_local="9091"
    _rpc_port_tunnel="9999"
    _sshfs_mountpoint="/mnt/sshfs-remote"
    _systemd_service="transmission-daemon"
    #+ youtube
    _drop_file_yt="${_drop_dir}/youtube.drop"
    _media_player_bin="/usr/local/bin/mpv"
fi


### logic
_url="$(echo "$1" | sed -e 's%fjyt://%%')";

# create drop file
echo "$_url" > "$_drop_file_yt"

exit 0
