#!/bin/sh
#
## BitTorrent URL handler for Firejail
#+ (1) `firejail-handler-bittorrent.desktop` defines a custom
#+ handler for magnet/.torrent hyperlinks
#+ (2) this script saves a drop file containing the URL at a read/write
#+ accessible location inside the sandbox
#+ (3) outside the sandbox `firejail-handler-bittorrent-ctl` uses inotifywait to pick up
#+ the URL and relays it to a fully sandboxed BitTorrent application
#+ (defaults to local transmission-daemon)

# shellcheck disable=SC2034

### vars
## source common settings
_settings_file="firejail-handler-settings-extra.inc"
if [ -f "${HOME}/.config/firejail/${_settings_file}" ]; then
    #+ use settings defined by user
    . "${HOME}/.config/firejail/${_settings_file}"
elif [ -f "/etc/firejail/${_settings_file}" ]; then
    #+ use system-wide settings
    . "/etc/firejail/${_settings_file}"
else
    #+ fall back to hard-coded values
    if [ "$(which xdg-user-dir)" ]; then
	_drop_dir="$(xdg-user-dir DOWNLOAD)"
    else
	_xdg_config_home="$(env | grep -c "XDG_CONFIG_HOME")"
	if [ "$_xdg_config_home" = 1 ]; then
	    if [ -s "${XDG_CONFIG_HOME}/user-dirs.dirs" ]; then
		_drop_dir="$(grep "^XDG_DOWNLOAD_DIR=" "${XDG_CONFIG_HOME}/user-dirs.dirs" | awk '{split($0,a,"="); print a[2]}' | sed 's/"//g')"
	    fi
	elif [ -s "${HOME}/.config/user-dirs.dirs" ]; then
	    _drop_dir="$(grep "^XDG_DOWNLOAD_DIR=" "${HOME}/.config/user-dirs.dirs" | awk '{split($0,a,"="); print a[2]}' | sed 's/"//g')"
	else
	    _drop_dir="${HOME}/Downloads"
	fi
    fi
    # bittorrent client watch dir for .torrent files
    _download_dir="$_drop_dir"
    ## drop dir location where the URL data will be saved temporarily
    #+ IMPORTANT: this needs to be read/write accessible in the sandbox
    _drop_dir="${_drop_dir}/.firejail-dropzone"
    ## protocol handlers
    #+ bittorrent
    _drop_file_bt="${_drop_dir}/bittorrent.drop"
    _media_dl_mode="local"
    _rpc_bin="/usr/local/bin/transmission-remote"
    _rpc_port_local="9091"
    _rpc_port_tunnel="9999"
    _sshfs_mountpoint="/mnt/sshfs-remote"
    _systemd_service="transmission-daemon"
    #+ youtube
    _drop_file_yt="${_drop_dir}/youtube.drop"
    _media_player_bin="/usr/local/bin/mpv"
fi


### logic
# local / remote daemon support
if [ "$_media_dl_mode" = "local" ]; then
    # LOCAL daemon
    _download_dir="$_download_dir"
    _local_daemon_status="$(systemctl is-active "$_systemd_service")"
    if [ "$_local_daemon_status" = "inactive" ]; then
	sudo systemctl start "$_systemd_service"
    fi
    _rpc_port="$_rpc_port_local"
else
    # REMOTE daemon (via SSH tunnel)
    _download_dir="${_sshfs_mountpoint}/${_download_dir}"
    _rpc_port="$_rpc_port_tunnel"
fi

## process requests
if [ "$1" ]; then
    case "$1" in
	magnet\:\?*)
	    #+ create drop file
	    echo "$1" > "$_drop_file_bt"
	    ;;
	*\.torrent)
	    #+ add .torrent file to configured watch dir in bittorrent client
	    mv -f "$1" "$_download_dir"
	    #+ create drop file
	    echo "$1" > "$_drop_file_bt"
	    ;;
    esac
else
    # no param
    exit 1
fi

exit 0
